# These are supported funding model platforms

github: [the-memoize-project]
# patreon: the-memoize-project
# open_collective: memoize
# ko_fi: the-memoize-project
# tidelift: npm/@the-memoize-project/token
# community_bridge: memoize
# liberapay: the-memoize-project
# issuehunt: the-memoize-project
# custom: ['https://memoize.dev/sponsor']
